name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#       name: Check out code
      
#     - uses: mr-smithers-excellent/docker-build-push@v5
#       name: Build & push Docker image
#       with:
#         image: test-workflow
#         tags: latest,${GITHUB_REF##*/}-${GITHUB_SHA}
#         registry: 793632633845.dkr.ecr.ap-southeast-1.amazonaws.com
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    deploy:      
      runs-on: ubuntu-latest
      steps:
        - name: executing remote ssh commands using ssh key
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ubuntu
            key: ${{ secrets.PRIVATE_KEY }}
            port: 22
            script: mkdir som
#       - name: ls -a via OPEN SSH Private Key
#         uses: fifsky/ssh-action@master
#         with:
#           command: |
#             pwd
#             ls -a
#             mkdir test
#           host: ${{ secrets.HOST }}
#           user: ubuntu
#           key: ${{ secrets.PRIVATE_KEY}}
#           args: "-tt"
